---
spring:
  application:
    name: spring-rest
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/aula6-taweb
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    
  mvc:
    dispatch-options-request: true    
server:
  port: 8020